server:
  port: 9295
baseurl: https://api.zippopotam.us/
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: password
    max_active: 30
    max_idle: 8
    min_idle: 0
    lettuce:
      shutdown-timeout: 3000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0

  graphql:
    graphiql:
      enabled: true
