server:
  port: 9295
baseurl: https://api.zippopotam.us/
spring:
  redis:
    host: localhost
    port: 6379
    password :  password
    lettuce:
      shutdown-timeout: 3000
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 0

  graphql:
    graphiql:
      enabled: true
